### ISSUE TITLE
Undefined reference to SSLv2_client_method

### ISSUE THREAD

**Issue by jdandrea** [philipgloyne/apachebench-for-multi-url#1]
Unable to patch on Ubuntu 14.04 (Apache/2.4.7, ApacheBench/2.3).

Note that I had to add `-lssl` and `-lcrypto` in order to avoid a lot of undefined references. Continuing to research.

```
$ gcc -I /usr/include/apr-1.0 -I /usr/include/apache2 ab.c -o ab -lm -lapr-1 -laprutil-1 -lssl -lcrypto
ab.c: In function ‘main’:
ab.c:2273:26: warning: assignment makes pointer from integer without a cast [enabled by default]
                     meth = SSLv2_client_method();
                          ^
/tmp/cciW0s10.o: In function `main':
ab.c:(.text+0x5ee5): undefined reference to `SSLv2_client_method'
collect2: error: ld returned 1 exit status
```

**Comment by jdandrea** [comment]
Using the ab binary provided in this repository in the meantime. :)

**Comment by mbsimonovic** [comment]
precompiled binary doesn't work on xenial, I'm getting segfaults :/ 

Can this be the reason (and solution): [https://mta.openssl.org/pipermail/openssl-dev/2016-March/005807.html](https://mta.openssl.org/pipermail/openssl-dev/2016-March/005807.html) -  they removed and then added SSLv2 methods? The fix was commited on Mar 7, 2016, and xenial has openssl v 1.0.2g which was released on Mar 1, 2016, so not in. 

@jdandrea **Update**: Just compiled openssl v1.0.2l and successfully compiled apachebench-for-multi-url against it. For the reference, full command:

```
gcc  -I /usr/include/apr-1.0 -I /usr/include/apache2 -I /usr/local/ssl/include/openssl -L /usr/local/ssl/lib  ab.c -o ab -lm -lapr-1 -laprutil-1 -lssl -lcrypto -ldl 
```

System details: 

- ApacheBench v2.4.1 (latest master checkout)
- libapr1-dev v1.5.2-3
- apache2-dev v2.4.18-2ubuntu3.4
- gcc version 5.4.0 20160609
- Ubuntu xenial, kernel 4.4.0-79-generic

**Comment by Popolon** [comment]
I don't know how to do pull request now, this changed a lot since last time I done one on Github.
Could you please merge with this commit, it fix compilation with current versions of OpenSSL.

https://github.com/Popolon/apachebench-for-multi-url/commit/7f854625fc36898d7be2210b80095dc05506621f

**Comment by philipgloyne** [comment]
Merged. Thanks both.
